services:
  - type: web
    name: collins
    env: python
    buildCommand: "apt-get update && apt-get install -y ffmpeg espeak-ng && pip install -r requirements.txt"
    startCommand: "python app.py"
